# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\"H\n\x0f\x45ntityOrLiteral\x12\x10\n\x06\x65ntity\x18\x01 \x01(\rH\x00\x12\x11\n\x07literal\x18\x02 \x01(\tH\x00\x42\x10\n\x0e\x65ntity_literal\"N\n\x06Triple\x12\x0f\n\x07subject\x18\x01 \x01(\r\x12\x11\n\tpredicate\x18\x02 \x01(\r\x12 \n\x06object\x18\x03 \x01(\x0b\x32\x10.EntityOrLiteral\"p\n\tQualifier\x12\x1a\n\x12qualifier_relation\x18\x01 \x01(\r\x12)\n\x0fqualifier_value\x18\x02 \x01(\x0b\x32\x10.EntityOrLiteral\x12\x1c\n\x14\x63orresponding_triple\x18\x04 \x01(\r\"\xa3\x01\n\x05Query\x12\x18\n\x07triples\x18\x01 \x03(\x0b\x32\x07.Triple\x12\x1e\n\nqualifiers\x18\x02 \x03(\x0b\x32\n.Qualifier\x12&\n\x0c\x65\x61sy_targets\x18\x03 \x03(\x0b\x32\x10.EntityOrLiteral\x12&\n\x0chard_targets\x18\x04 \x03(\x0b\x32\x10.EntityOrLiteral\x12\x10\n\x08\x64iameter\x18\x05 \x01(\r\"$\n\tQueryData\x12\x17\n\x07queries\x18\x01 \x03(\x0b\x32\x06.Queryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENTITYORLITERAL._serialized_start=15
  _ENTITYORLITERAL._serialized_end=87
  _TRIPLE._serialized_start=89
  _TRIPLE._serialized_end=167
  _QUALIFIER._serialized_start=169
  _QUALIFIER._serialized_end=281
  _QUERY._serialized_start=284
  _QUERY._serialized_end=447
  _QUERYDATA._serialized_start=449
  _QUERYDATA._serialized_end=485
# @@protoc_insertion_point(module_scope)
