SELECT DISTINCT ?s0 ?p0 ?o0_o1_s2_var ?s1 ?p1 ?p2 (group_concat(distinct ?o2; separator="|") AS ?o2_targets)  ?qr0i0 ?qv0i0 ?qr1i1 ?qv1i1 ?qr2i2 ?qv2i2 ?diameter WHERE {
	BIND ("?var0" as ?o0_o1_s2_var)
	BIND (2 as ?diameter)

    graph <split:train>{
        << ?s0 ?p0 ?o0_o1_s2 >> ?qr0i0 ?qv0i0 .
        << ?s1 ?p1 ?o0_o1_s2 >> ?qr1i1 ?qv1i1 .
        << ?o0_o1_s2 ?p2 ?o2 >> ?qr2i2 ?qv2i2 .
    }



    #Prevent collapsing to 2 hop
	FILTER(!(?s0=?s1 && ?p0=?p1))
	#Prevent multiple permutations
	FILTER(str(?s0) < str(?s1) ||
              (str(?s0)=str(?s1) && str(?p0) < str(?p1) ))
	FILTER(isIRI(?s0) && isIRI(?s1) && isIRI(?o0_o1_s2) && isIRI(?o2))



### restrictions ###


} GROUP BY ?s0 ?p0 ?o0_o1_s2_var ?s1 ?p1 ?p2 ?qr0i0 ?qv0i0 ?qr1i1 ?qv1i1 ?qr2i2 ?qv2i2 ?diameter