# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# based on https://github.com/actions/starter-workflows/blob/d9236ebe5585b1efd5732a29ea126807279ccd56/ci/python-package.yml

name: Python package

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip and build dependencies
        run: | # setuptools is fixed to 58 until pyhash gets compatible with it
          python3 -m pip install --upgrade pip setuptools wheel
      # - name: Install PyTorch Geometric
        # PyTorch Geometric requires some special treatment
        ## No longer, it seems. Now added to normal dependencies.
        #run: |
        #  pip install torch_geometric
        #  pip install pyg_lib torch_scatter torch_sparse torch_cluster \
        #  torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
        # python3 -m pip install torch-scatter torch-sparse torch-cluster torch-spline-conv \
        # torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html
        # python -m pip install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        # python -m pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
        # python -m pip install torch-geometric
      - name: Install packages
        run: |
          python3 -m pip install .[test]
      - name: Lint with flake8
        run: |
          flake8 src tests
      - name: Check typing with mypy
        run: |
          mypy  --strict --install-types --non-interactive src tests
      - name: Test with pytest
        run: |
          py.test tests -m "not full_data"
